FROM rust:latest

WORKDIR /usr/src/app

ENV SQLX_OFFLINE=true

# RUN rustup target add aarch64-unknown-linux-musl
RUN rustup target add x86_64-unknown-linux-musl

RUN apt-get update && apt-get install -y musl-tools gcc-aarch64-linux-gnu

RUN cargo install cargo-watch

COPY ./expr .

ENV SQLX_OFFLINE=true

# RUN cargo build --target aarch64-unknown-linux-musl --release
RUN cargo build --target x86_64-unknown-linux-musl

CMD ["cargo", "watch", "-x", "run -- -s"]
